#!/usr/bin/env python
from misc.utility.scons_hints import *
import os

Import("env")
Import("env_modules")

def get_addon_target():
    if env["target"] == "template_release":
        return "template_release"
    return "template_debug"

def get_addon_platform():
    return env["platform"].replace("linuxbsd", "linux")

dev_build_extension = ""
if env["dev_build"]:
    dev_build_extension += ".dev"

def get_sufix():
    suffix = ".{}.{}".format(get_addon_platform(), get_addon_target())
    suffix += dev_build_extension
    if env["precision"] == "double":
        suffix += ".double"
    suffix += "." + env["arch"]
    if not env["threads"]:
        suffix += ".nothreads"
    return suffix


os.system("scons static_build=yes platform=" + get_addon_platform() + " target=" + get_addon_target() + " arch=" + env["arch"] + " precision=" + env["precision"] + " threads=" + str(env["threads"]) + " dev_build=" + str(env["dev_build"]))

platform = get_addon_platform()
target = get_addon_target()
arch = env["arch"]

if platform == "macos":
    base_path = f"#modules/sandbox/bin/addons/godot_sandbox/bin/libgodot_riscv.macos.{target}{dev_build_extension}.{arch}.framework/"
    base_file = f"{base_path}libgodot_riscv.macos.{target}{dev_build_extension}.{arch}"
elif platform == "ios":
    base_path = f"#modules/sandbox/bin/addons/godot_sandbox/bin/libgodot_riscv.ios.{target}{dev_build_extension}.{arch}.framework/"
    base_file = f"{base_path}libgodot_riscv.ios.{target}{dev_build_extension}.{arch}"
elif platform == "windows":
    base_path = "#modules/sandbox/bin/addons/godot_sandbox/bin"
    base_file = "godot_riscv"
else:
    base_path = "#modules/sandbox/bin/addons/godot_sandbox/bin"
    base_file = "godot_riscv{}".format(get_sufix())

env_gdextension = env_modules.Clone()
print("Using base path: {}".format(base_path))
print("Using base file: {}".format(base_file))
env.Append(LIBS=[base_file])
env.Append(LIBPATH=[base_path])

# Godot-cpp
cpp_base_path = "#modules/sandbox/ext/godot-cpp/bin"
if platform == "macos":
    cpp_base_file = f"{cpp_base_path}/libgodot-cpp.macos.{target}{dev_build_extension}.{arch}"
elif platform == "ios":
    cpp_base_file = f"{cpp_base_path}/libgodot-cpp.ios.{target}{dev_build_extension}.{arch}"
elif platform == "windows":
    cpp_base_file = "godot-cpp"
else:
    cpp_base_file = "godot-cpp{}".format(get_sufix())

env.Append(LIBS=[cpp_base_file])
env.Append(LIBPATH=[cpp_base_path])

# Sources
env_gdextension.add_source_files(env.modules_sources, "*.cpp")
