#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

def get_sufix():
    suffix = ".{}.{}".format(env["platform"], env["target"])
    if env.dev_build:
        suffix += ".dev"
    if env["precision"] == "double":
        suffix += ".double"
    suffix += "." + env["arch"]
    if not env["threads"]:
        suffix += ".nothreads"
    return suffix

# Libraries
if env["platform"] == "macos" or env["platform"] == "ios":
    base_path = "bin/addons/godot_sandbox/bin/libgodot_riscv{}.framework".format(get_sufix())
    base_file = "libgodot_riscv{}".format(get_sufix())
else:
    base_path = "bin/addons/godot_sandbox/bin"
    base_file = "libgodot_riscv{}".format(get_sufix())

# Flags
if env["platform"] != "windows" or env["use_mingw"]:
    env.Append(CXXFLAGS=["-std=c++20"])
else:
    env.Append(CXXFLAGS=["/std:c++20"])

# Sources
env_gdextension = env_modules.Clone()

env_gdextension.add_source_files(env.modules_sources, "*.cpp")
