#!/usr/bin/env python3
"""Regenerate builtin_api.gen.inc from godot-cpp's extension_api.json.

Run from the repository root:

    python3 src/safegdscript/generate_builtin_api.py

godot-cpp has no run-time enumeration API for the members of a built-in Variant
type, so the editor reads them from this table instead.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
API = os.path.join(ROOT, "ext", "godot-cpp", "gdextension", "extension_api.json")
OUT = os.path.join(ROOT, "src", "safegdscript", "builtin_api.gen.inc")

SKIP = {"Nil", "bool", "int", "float"}
SEPARATOR = "\\037"


def normalize(type_name):
    if not type_name:
        return "void"
    if type_name.startswith("typedarray::"):
        return "Array"
    if type_name.startswith("enum::") or type_name.startswith("bitfield::"):
        return "int"
    return type_name


def escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def arguments(entry):
    parts = []
    for argument in entry.get("arguments", []):
        text = "%s: %s" % (argument["name"], normalize(argument["type"]))
        if "default_value" in argument:
            text += " = " + argument["default_value"]
        parts.append(text)
    return SEPARATOR.join(escape(part) for part in parts)


def main():
    with open(API, "r", encoding="utf-8") as handle:
        api = json.load(handle)

    lines = [
        "// Generated by src/safegdscript/generate_builtin_api.py. Do not edit.",
        "",
    ]
    names = []
    for entry in api["builtin_classes"]:
        name = entry["name"]
        if name in SKIP:
            continue
        names.append(name)
        symbol = name

        members = entry.get("members", [])
        lines.append("static const BuiltinMember members_%s[] = {" % symbol)
        for member in members:
            lines.append('\t{ "%s", "%s" },' % (member["name"], normalize(member["type"])))
        lines.append("\t{ nullptr, nullptr }\n};")

        constants = entry.get("constants", [])
        lines.append("static const BuiltinMember constants_%s[] = {" % symbol)
        for constant in constants:
            lines.append('\t{ "%s", "%s" },' % (constant["name"], normalize(constant["type"])))
        lines.append("\t{ nullptr, nullptr }\n};")

        methods = entry.get("methods", [])
        lines.append("static const BuiltinMethod methods_%s[] = {" % symbol)
        for method in methods:
            lines.append('\t{ "%s", "%s", "%s", %s },' % (
                method["name"], normalize(method.get("return_type")),
                arguments(method), "true" if method.get("is_static") else "false"))
        lines.append("\t{ nullptr, nullptr, nullptr, false }\n};")

        constructors = entry.get("constructors", [])
        lines.append("static const char *const constructors_%s[] = {" % symbol)
        for constructor in constructors:
            lines.append('\t"%s",' % arguments(constructor))
        lines.append("\tnullptr\n};")
        lines.append("")

    lines.append("static const BuiltinClassInfo builtin_classes[] = {")
    for name in names:
        lines.append('\t{ "%s", members_%s, constants_%s, methods_%s, constructors_%s },'
                % (name, name, name, name, name))
    lines.append("\t{ nullptr, nullptr, nullptr, nullptr, nullptr }\n};")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    sys.stderr.write("wrote %s (%d types)\n" % (OUT, len(names)))


if __name__ == "__main__":
    main()
