name: Build iOS
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {arch: arm64, precision: single, extension: ""}
          - {arch: arm64, precision: double, extension: ".double"}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: 4.3
          path: godot
      - name: 🔗 GDExtension Build Single
        uses: ughuuu/godot-cpp-template/.github/actions/build@add-godot-repo-new-option
        with:
          platform: ios
          arch: ${{ matrix.arch }}
          build-target-type: template_release
          float-precision: ${{ matrix.precision }}
          godot-repo: godot

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-sandbox-ios-${{ matrix.arch }}-${{ matrix.precision }}
          path: |
            ${{ github.workspace }}/bin/**/libgodot_riscv.ios.template_release${{ matrix.extension }}.arm64.framework/**
          if-no-files-found: error
