name: Build iOS
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {arch: arm64, precision: single, extension: ""}
          - {arch: arm64, precision: double, extension: ".double"}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: 🔗 GDExtension Build Single
        uses: godotengine/godot-cpp-template/.github/actions/build@main
        with:
          platform: ios
          arch: ${{ matrix.arch }}
          build-target-type: template_release
          float-precision: ${{ matrix.precision }}
          godot-cpp-directory: ext/godot-cpp

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-sandbox-ios-${{ matrix.arch }}-${{ matrix.precision }}
          path: |
            ${{ github.workspace }}/bin/**/*.arm64
          if-no-files-found: error

      - name: Upload Artifact Static
        uses: actions/upload-artifact@v4
        with:
          name: static-sandbox-ios-${{ matrix.arch }}-${{ matrix.precision }}
          path: |
            ${{ github.workspace }}/bin/**/*.a
            ${{ github.workspace }}/ext/godot-cpp/**/*.a
          if-no-files-found: error
