name: Build Windows
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {arch: x86_32, precision: single}
          - {arch: x86_32, precision: double}
          - {arch: x86_64, precision: single}
          - {arch: x86_64, precision: double}
          - {arch: arm64, precision: single}
          - {arch: arm64, precision: double}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache .scons_cache
        uses: actions/cache@v4
        with:
          path: |
            .scons-cache/
            godot-cpp/.scons-cache/
          key: windows_${{ matrix.arch }}_${{ matrix.precision }}_template_release_cache      
          
      - uses: MinoruSekine/setup-scoop@v4.0.1

      - run: |
          scoop bucket add dorado https://github.com/chawyehsu/dorado
          scoop install dorado/llvm-mingw

      - name: Build godot-cpp Debug Build
        shell: sh
        env:
          SCONS_CACHE: godot-cpp/.scons-cache/
        run: |
          scons target=template_release platform=windows arch=${{ matrix.arch }} generate_bindings=yes precision=${{ matrix.precision }} use_mingw=no
        working-directory: godot-cpp/
      
      - name: Build GDExtension Debug Build
        shell: sh
        env:
          SCONS_CACHE: .scons-cache/
        run: |
          scons target=template_release platform=windows arch=${{ matrix.arch }} precision=${{ matrix.precision }} use_mingw=no
        working-directory: godot-cpp/

      - name: Cache .scons_cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.scons-cache/
            ${{ github.workspace }}/godot-cpp/.scons-cache/
          key: windows_${{ matrix.arch }}_${{ matrix.precision }}_template_release_cache

      - run: |
          scoop bucket add dorado https://github.com/chawyehsu/dorado
          install dorado/llvm-mingw

      - name: Upload Artifact Static
        uses: actions/upload-artifact@v4
        with:
          name: static-sandbox-windows-${{ matrix.arch }}-${{ matrix.precision }}
          path: |
            ${{ github.workspace }}/bin/**/*.a
            ${{ github.workspace }}/ext/godot-cpp/**/*.a
          if-no-files-found: error
